[project]
name = "safeparse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "passlib[bcrypt]>=1.7.4",
    "prompt-toolkit>=3.0.51",
    "rich>=14.0.0",
    "textual>=3.7.1",
]
